# IDE
kotlin.code.style=official
org.gradle.jvmargs=-Xmx1G
org.gradle.warning.mode=all
# Check these on https://fabricmc.net/develop/
minecraftVersion=1.21.5
yarnMappings=1.21.5+build.1
loaderVersion=0.16.14
# Fabric API
fabricVersion=0.124.0+1.21.5
loomVersion=1.10-SNAPSHOT
# Mod Properties
modVersion=2025.5.1
mavenGroup=dev.syoritohatsuki
archivesBaseName=death-counter
# Kotlin
systemProp.kotlinVersion=2.1.21
fabricKotlinVersion=1.13.3+kotlin.2.1.21
# Dependancy
ktorVersion=3.1.3