# IDE
kotlin.code.style=official
org.gradle.jvmargs=-Xmx1G
org.gradle.warning.mode=all
# Check these on https://fabricmc.net/develop/
minecraftVersion=1.21.2
yarnMappings=1.21.2+build.1
loaderVersion=0.16.7
# Fabric API
fabricVersion=0.106.1+1.21.2
loomVersion=1.8-SNAPSHOT
# Mod Properties
modVersion=2024.12.3
mavenGroup=dev.syoritohatsuki
archivesBaseName=death-counter
# Kotlin
systemProp.kotlinVersion=2.0.20
fabricKotlinVersion=1.12.2+kotlin.2.0.20
# Dependancy
ktorVersion=3.0.2